name: Metropolis Gallery
favicon: null
layout_spectrum: 0.86066
typography_spectrum: 0.2765726794023067
title: Metropolis Gallery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2221'
    - '#ffffff'
    - '#bbb4a2'
    - '#7b625d'
    - '#9b9482'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
