name: Metropolis
favicon: null
layout_spectrum: 0.70865
typography_spectrum: 0.2765726794023067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2221'
    - '#ffffff'
    - '#bbb4a2'
    - '#7b625d'
    - '#9b9482'
  brandStrength: 0.5625
  lightness: 0.3931955015286803
  saturation: 0.3490336933173239
  rhythmicContrast: 0.11080105369910598
purpose: []
